apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  SA_GATEWAY_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  SA_GATEWAY_SERVER__HOST: {{ .Values.config.server.host | quote }}
  SA_GATEWAY_SERVER__PORT: {{ .Values.config.server.port | quote }}
  SA_GATEWAY_NATS__URL: {{ .Values.config.nats.url | default (printf "nats://%s-nats:4222" .Release.Name) | quote }}
  SA_GATEWAY_NATS__FETCH_SUBJECT: {{ .Values.config.nats.fetchSubject | quote }}
  SA_GATEWAY_NATS__ANALYZE_SUBJECT: {{ .Values.config.nats.analyzeSubject | quote }}
  SA_GATEWAY_NATS__ANALYZE_AGENT_SUBJECT: {{ .Values.config.nats.analyzeAgentSubject | quote }}
  SA_GATEWAY_NATS__LIST_APPS_SUBJECT: {{ .Values.config.nats.listAppsSubject | quote }}
  SA_GATEWAY_NATS__FETCH_TIMEOUT: {{ .Values.config.nats.fetchTimeout | quote }}
  SA_GATEWAY_NATS__ANALYZE_TIMEOUT: {{ .Values.config.nats.analyzeTimeout | quote }}
  SA_GATEWAY_NATS__ANALYZE_AGENT_TIMEOUT: {{ .Values.config.nats.analyzeAgentTimeout | quote }}
  SA_GATEWAY_NATS__LIST_APPS_TIMEOUT: {{ .Values.config.nats.listAppsTimeout | quote }}
  SA_GATEWAY_MAX_STORED_TASKS: {{ .Values.config.maxStoredTasks | quote }}
