apiVersion: v2
name: spark-advisor-storage-connector
description: Spark Advisor Storage Connector — reads event logs from HDFS, S3, or GCS
type: application
version: 0.1.15 # x-release-please-version
appVersion: "0.1.15" # x-release-please-version
