apiVersion: v2
name: spark-advisor-frontend
description: Spark Advisor Frontend — React SPA served by nginx
type: application
version: 0.1.16 # x-release-please-version
appVersion: "0.1.16" # x-release-please-version
