apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.config.prometheusUrl }}
        isDefault: true
        editable: false
      - name: Tempo
        type: tempo
        access: proxy
        url: {{ .Values.config.tempoUrl }}
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: ''
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: "Spark Advisor"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false
  spark-advisor.json: |
    {{- .Files.Get "dashboards/spark-advisor.json" | nindent 4 }}
  spark-advisor-nats.json: |
    {{- .Files.Get "dashboards/spark-advisor-nats.json" | nindent 4 }}
  spark-advisor-rules.json: |
    {{- .Files.Get "dashboards/spark-advisor-rules.json" | nindent 4 }}
