apiVersion: v2
name: spark-advisor-tempo
description: Grafana Tempo distributed tracing backend for Spark Advisor
type: application
version: 0.1.16 # x-release-please-version
appVersion: "0.1.16" # x-release-please-version
