apiVersion: v2
name: spark-advisor-prometheus
description: Prometheus metrics server for Spark Advisor monitoring
type: application
version: 0.1.10 # x-release-please-version
appVersion: "0.1.10" # x-release-please-version
