analyzer:
  config:
    nats:
      url: "nats://spark-advisor-nats:4222"
    ai:
      enabled: true

gateway:
  config:
    nats:
      url: "nats://spark-advisor-nats:4222"

frontend:
  config:
    gatewayUrl: "http://spark-advisor-gateway:8080"

hs-connector:
  config:
    nats:
      url: "nats://spark-advisor-nats:4222"
    historyServerUrl: "http://spark-history:18080"

storage-connector:
  enabled: false
  config:
    nats:
      url: "nats://spark-advisor-nats:4222"

nats:
  config:
    jetstream:
      enabled: true

prometheus:
  enabled: false

tempo:
  enabled: false

grafana:
  enabled: false
