apiVersion: v2
name: spark-advisor-grafana
description: Grafana dashboard for Spark Advisor monitoring
type: application
version: 0.1.12 # x-release-please-version
appVersion: "0.1.12" # x-release-please-version
