apiVersion: v2
name: spark-advisor-hs-connector
description: Spark Advisor HS-Connector — History Server poller and on-demand fetcher
type: application
version: 0.1.8 # x-release-please-version
appVersion: "0.1.8" # x-release-please-version
